### ISSUE TITLE
Add additional option for area_fill

### ISSUE THREAD

**Issue by veggabo** [Ringomed/ggvanced#6]
Hi @Ringomed!

One more request from me:
Could you alter the `area_fill` argument to accept specific group/observation names? I only want to fill one of the observations. 

**An example:** 
In the figure below, I only want the area for "threshold" to be filled, and not for "Norway".

![image](https://github.com/Ringomed/ggvanced/assets/47369762/ed01f8ee-22d2-49af-98ba-393b68356fcc)

**Comment by Ringomed** [comment]
Hi @veggabo,

since the final chart is a ggplot2 object, it is actually possible to do this using existing ggplot functions. Just modify the code below to suit your needs.

`iris_summary <- iris %>% 
  dplyr::group_by(Species) %>% 
  dplyr::summarise(across(everything(), mean))`

`ggspider(iris_summary) +
  scale_fill_manual(values = c("setosa" = "blue"), na.value = "transparent") +
  scale_color_manual(values = c("setosa" = "blue", "versicolor" = "red", "virginica" = "green"))`

The fill function controls the fill color of the shapes, and the color the color of the external lines. The na.value argument specifies the color for the groups that were not assigned a specific value in the named vector.

Let me know if you have any trouble adapting this to your data,
Zvonimir

**Comment by veggabo** [comment]
Aha, thanks for the tip! I managed to make it work as intended.
